name: Deployment Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  deployments: write
  statuses: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      web_src: ${{ steps.changes.outputs.web_src }}
      api_src: ${{ steps.changes.outputs.api_src }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          base: main
          filters: |
            web_src:
              - 'src/web/**'
            api_src:
              - 'src/api/**'

  # バックエンドをデプロイする場合
  dbmigrate:
    needs: [changes]
    if: ${{ needs.changes.outputs.api_src == 'true' && needs.changes.outputs.web_src == 'true' }}
    uses: ./.github/workflows/api-db-migrate.yml

  sidekiq:
    needs: [dbmigrate]
    uses: ./.github/workflows/api-deploy.yml

  api:
    needs: [dbmigrate]
    uses: ./.github/workflows/api-deploy.yml

  web:
    needs: [api]
    uses: ./.github/workflows/web-deploy.yml 

  # フロントだけデプロイする場合
  web_only:
    if: ${{ needs.changes.outputs.api_src == 'false' && needs.changes.outputs.web_src == 'true' }}
    needs: [changes]
    uses: ./.github/workflows/web-deploy.yml
